### ISSUE TITLE
Restarting a move is a bit too complicated

### ISSUE THREAD

**Issue by yagu0** [kreibaum/pacosako#41]
Players are used to click on a piece, and then either re-click it or click elsewhere to cancel (putting back the piece on the board). In the case of the first move (not inside a chain), the button "Restart move" shouldn't be required. Because people click everywhere a lot :-) That being said, when a sequence of unions/releases started, then this button seems the right way to go.

(Edited after reading #33).

**Comment by kreibaum** [comment]
Yeah, I agree. Saw the same issue with another new player yesterday as well.

I wonder if I should put a "Restart move" overlay somewhere on the board when the player is currently chaining. But I don't really know where I would best put it.

**Comment by kreibaum** [comment]
Latest commit fixes this for the basic situation.

You still need to click twice, if you want to drop a piece down and lift another piece. But this is because there is not enough game logic implemented in the client.

**Comment by Rafluijt** [comment]
I think this is only an issue when you use a mouse. I’m using a touchscreen and never had this issue.

A mouse click is used to place the piece on the position where you want to move to.
Maybe you can use a right click button to cancel this operation?

Kind regards,

Raimond Fluijt

**Comment by kreibaum** [comment]
I am reasonably happy with how it is now, right click would be missing for tablet users so I discarded the idea.
