### ISSUE TITLE
Integrate login system

### ISSUE THREAD

**Issue by kreibaum** [kreibaum/pacosako#66]
I want people to log in to pacoplay with their discord account. This already works on the hidden page https://pacoplay.com/login but the server doesn't do anything with this information.

- [x] Implement Discord OAuth
- [x] Let the Websocket know about the user that is signed in.
- [x] Store the users that played a game in the database.
- [x] Show the users that played a game.
- [x] Consider implementing an alternative fake login to develop locally without OAuth secrets being available. That way I can't publish them on accident.

For the initial version, the profile pictures should be out of scope so I don't have to think about the legal issues with storing other peoples profile pictures / linking to discord.

**Comment by Rafluijt** [comment]
Good morning Rolf,

I tried to login with my discord page.
It is asking. For a login and password.

For the login I tried to login with my login name.
That didn’t work, when i tried it with my registered email is accepted my login attempt.
Can you see I logged in?

Nice to see this progress af accounts on pacopplay.com.

Kind regards,

Raimond Fluijt

**Comment by kreibaum** [comment]
I checked the list of accounts and it only has my own account. So it looks like it didn't work for you. We should look into that at some point when I keep working on that. Probably after I make the return page more meaningful.

**Comment by kreibaum** [comment]
I want people to hide their discord avatar and use a randomly generated (but fixed) avatar instead. This can be a Gravatar like avatar and I can just proxy those from some API like

https://seccdn.libravatar.org/avatar/204bedcd9a44b3e1db26e7619bca694d?s=200&forcedefault=y&default=identicon

**Comment by kreibaum** [comment]
Discord auth works now and is live for everyone to use :-)
