### ISSUE TITLE
Add a "Puzzle Finder" to search for random puzzles

### ISSUE THREAD

**Issue by kreibaum** [kreibaum/pacosako#80]
The page should allow you to choose some criteria and then search the space of random Paco Ŝako boards for one that matches the description.

You'll then get a new-tab link to the "design" page where you can try it out.

This is enabled by the work done on #68.

**Comment by kreibaum** [comment]
Looks like this is duplicated by #94 with the comment

This should be a toolkit that allows you to specify what you are looking for and then helps you find random positions that match these parameters or match these parameters best.

E.g.

    is promotion allowed/forbidden/required?
    Should there be long chains for both sides or just for one?
    Which random generator should be used?

This probably makes a lot more sense after you can save puzzles into your account and share them.

**Comment by DerOrigamiMann** [comment]
What about a way to see (random) one of the saved games (criteria: won, without time out) before the last move is done. If you can also search if the last move has 3+ "steps" that should be a "puzzle".

**Comment by kreibaum** [comment]
This isn't something that is important right now and it isn't a bug either. Closing the issue.
